### ISSUE TITLE
Update launch_path and href values in manifest.webapp for release

### ISSUE THREAD

**Issue by srottenberg** [openberg/lector-dev#145] opened 2014-12-15 11:14 UTC
In manifest.webapp, the `launch_app` and `href` values should be updated before final release : from `/lector-dev/index.html` to `/lector/index.html`

The solution will probably be a short release script.

**Comment by Yoric** [comment] 2014-12-16 12:45
Fixed by feb484eb613d86fc1ebcd6bc2e71245bab48c642.

**Comment by Yoric** [comment] 2014-12-16 21:18
Actually, I'm wrong. The issue isn't fixed at all, my bad.

**Comment by srottenberg** [comment] 2015-01-05 12:28
I followed the instructions suggested on this link : http://jekyllrb.com/docs/github-pages/#project-page-url-structure

**Comment by Yoric** [comment] 2015-01-07 12:51
Fixed by above pull request.

**Closed as completed by Yoric** 2015-01-07 12:51 UTC
Labels: OS: Open Web App
